news:
  rss_urls:
    - "https://news.yahoo.co.jp/rss/topics/it.xml"
    - "https://news.yahoo.co.jp/rss/topics/domestic.xml"
    - "https://news.yahoo.co.jp/rss/topics/world.xml"
    - "https://news.yahoo.co.jp/rss/topics/business.xml"
  ranking_rss_url: "https://news.yahoo.co.jp/rss/topics/top-picks.xml"
  num_articles: 5
  keywords:
    - AI
  prompt_template: |
    以下のニュースについて、簡潔に要約してください。
    さらに、そのニュースの背景や関連情報もわかりやすく説明してください。
    なお、背景や関連情報は1記事当たり15秒程度で読めるように簡潔にまとめてください。

    ニュースタイトル: {title}
    URL: {link}
