news:
  rss_urls:
    - "https://news.yahoo.co.jp/rss/topics/it.xml"
    - "https://news.yahoo.co.jp/rss/topics/domestic.xml"
    - "https://news.yahoo.co.jp/rss/topics/world.xml"
    - "https://news.yahoo.co.jp/rss/topics/business.xml"
  ranking_rss_url: "https://news.yahoo.co.jp/rss/topics/top-picks.xml"
  num_articles: 5
  keywords:
    - AI
