name: Send Daily News

on:
  schedule:
    - cron: "0 23 * * *" # 毎日8時(JST)に実行（UTC23時）
    - cron: "0 10 * * *" # 毎日19時(JST)に実行（UTC10時）
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install feedparser pyyaml openai

      - name: Run news script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}

        run: python main.py
